elevcentralen:
    username: ""
    password: ""
database: data/main.db
images: data/images
screenshots: data/screenshots
chromedriver: /usr/local/app/chromedriver/chromedriver
user_agent: "Mozilla/5.0 (iPad; CPU OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1"
